spring.application.name=shop

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=shopdb;trustServerCertificate=true
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=sa
spring.datasource.password=Zr69749411

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

logging.level.org.springframework.boot=DEBUG
# ---- application.properties ----
neshan.api-key=service.0f24a4f611a744bcbdac2fd79033f93a

# Relax Tomcat query character validation to allow pipe (|) character
server.tomcat.relaxed-query-chars=|
server.tomcat.relaxed-path-chars=|
